# Generated by Django 4.1 on 2022-08-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BasicSite', '0002_remove_restaurant_place_remove_waiter_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Unnamed User', max_length=150)),
                ('age', models.IntegerField(blank=True, max_length=9)),
                ('email', models.EmailField(default=None, max_length=100, unique=True)),
                ('password', models.CharField(help_text=True, max_length=16)),
                ('graduated', models.BooleanField(blank=True, default=True)),
                ('reason', models.TextField(blank=True, default='Without description', help_text=True, max_length=5000)),
                ('level', models.CharField(choices=[('1', 'Junior'), ('2', 'Middle'), ('3', 'Senior')], max_length=150)),
            ],
        ),
    ]
